// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartBearServer.Data;

#nullable disable

namespace SmartBearServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411034011_AddNicknameToDevice")]
    partial class AddNicknameToDevice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartBearServer.Model.BannedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("banned_words");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4622),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "tu sat"
                        },
                        new
                        {
                            Id = 2,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4625),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "giet nguoi"
                        },
                        new
                        {
                            Id = 3,
                            Category = "drug",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4627),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "ma tuy"
                        },
                        new
                        {
                            Id = 4,
                            Category = "adult",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4629),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "sex"
                        },
                        new
                        {
                            Id = 5,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4630),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "vu khi"
                        },
                        new
                        {
                            Id = 6,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4632),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "suicide"
                        },
                        new
                        {
                            Id = 7,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4633),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "kill"
                        },
                        new
                        {
                            Id = 8,
                            Category = "drug",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4635),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "drugs"
                        },
                        new
                        {
                            Id = 9,
                            Category = "adult",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4636),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "porn"
                        },
                        new
                        {
                            Id = 10,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4638),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "weapon"
                        },
                        new
                        {
                            Id = 11,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4639),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "bomb"
                        },
                        new
                        {
                            Id = 12,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4640),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "terrorist"
                        },
                        new
                        {
                            Id = 13,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4642),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "dao"
                        },
                        new
                        {
                            Id = 14,
                            Category = "security",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4643),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "hack"
                        },
                        new
                        {
                            Id = 15,
                            Category = "security",
                            CreatedAt = new DateTime(2026, 4, 11, 3, 40, 11, 375, DateTimeKind.Utc).AddTicks(4644),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "password"
                        });
                });

            modelBuilder.Entity("SmartBearServer.Model.ChildProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int?>("AllowedEndHour")
                        .HasColumnType("integer");

                    b.Property<int?>("AllowedStartHour")
                        .HasColumnType("integer");

                    b.Property<string>("BlockedTopics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GraceEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscribedSubjects")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SubscriptionPlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubscriptionStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubscriptionStatus")
                        .HasColumnType("integer");

                    b.Property<string>("WhitelistTopics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("ChildProfiles");
                });

            modelBuilder.Entity("SmartBearServer.Model.DailyUsage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AiRequestCount")
                        .HasColumnType("integer");

                    b.Property<int>("AudioSecondsUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "DateUtc")
                        .IsUnique();

                    b.ToTable("DailyUsages");
                });

            modelBuilder.Entity("SmartBearServer.Model.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DeviceId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("bear_devices");
                });

            modelBuilder.Entity("SmartBearServer.Model.DeviceCredential", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "TokenHash")
                        .IsUnique();

                    b.ToTable("DeviceCredentials");
                });

            modelBuilder.Entity("SmartBearServer.Model.InteractionHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ChildProfileId")
                        .HasColumnType("text");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId");

                    b.ToTable("InteractionHistories");
                });

            modelBuilder.Entity("SmartBearServer.Model.SmartAlarm", b =>
                {
                    b.Property<string>("AlarmId")
                        .HasColumnType("text")
                        .HasColumnName("alarm_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<int>("Hour")
                        .HasColumnType("integer")
                        .HasColumnName("hour");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<string>("WakeUpMessage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("wake_up_message");

                    b.HasKey("AlarmId");

                    b.HasIndex("DeviceId");

                    b.ToTable("smart_alarms");
                });

            modelBuilder.Entity("SmartBearServer.Model.Song", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("SmartBearServer.Model.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanPlayMusic")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanTellStoriesOnUserSpeech")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUseLearningAI")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanType")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceMonthly")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanPlayMusic = true,
                            CanTellStoriesOnUserSpeech = true,
                            CanUseLearningAI = false,
                            Description = "Basic music and stories.",
                            IsActive = true,
                            Name = "Basic Plan",
                            PlanType = 1,
                            PriceMonthly = 0m
                        },
                        new
                        {
                            Id = 2,
                            CanPlayMusic = true,
                            CanTellStoriesOnUserSpeech = true,
                            CanUseLearningAI = true,
                            Description = "Unlimited AI Learning.",
                            IsActive = true,
                            Name = "Premium Plan",
                            PlanType = 2,
                            PriceMonthly = 99m
                        });
                });

            modelBuilder.Entity("SmartBearServer.Model.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_id");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SmartBearServer.Model.ChildProfile", b =>
                {
                    b.HasOne("SmartBearServer.Model.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("SmartBearServer.Model.Device", b =>
                {
                    b.HasOne("SmartBearServer.Model.ChildProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("SmartBearServer.Model.User", "ParentUser")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentUser");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SmartBearServer.Model.InteractionHistory", b =>
                {
                    b.HasOne("SmartBearServer.Model.ChildProfile", null)
                        .WithMany("Interactions")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartBearServer.Model.SmartAlarm", b =>
                {
                    b.HasOne("SmartBearServer.Model.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SmartBearServer.Model.ChildProfile", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("SmartBearServer.Model.User", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
