// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartBearServer.Data;

#nullable disable

namespace SmartBearServer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504023955_AddDailyCandyLimitToProfile")]
    partial class AddDailyCandyLimitToProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartBearServer.Model.BannedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.ToTable("banned_words");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6186),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "tu sat"
                        },
                        new
                        {
                            Id = 2,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6189),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "giet nguoi"
                        },
                        new
                        {
                            Id = 3,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6190),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "dam nhau"
                        },
                        new
                        {
                            Id = 4,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6191),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "danh nhau"
                        },
                        new
                        {
                            Id = 5,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6192),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "tu vong"
                        },
                        new
                        {
                            Id = 6,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6194),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "mau me"
                        },
                        new
                        {
                            Id = 7,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6194),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "bat coc"
                        },
                        new
                        {
                            Id = 10,
                            Category = "drug",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6195),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "ma tuy"
                        },
                        new
                        {
                            Id = 11,
                            Category = "drug",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6196),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "can sa"
                        },
                        new
                        {
                            Id = 12,
                            Category = "drug",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6228),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "thuoc phien"
                        },
                        new
                        {
                            Id = 13,
                            Category = "drug",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6229),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "hit ke"
                        },
                        new
                        {
                            Id = 14,
                            Category = "alcohol",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6229),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "uong ruou"
                        },
                        new
                        {
                            Id = 15,
                            Category = "tobacco",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6230),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "hut thuoc"
                        },
                        new
                        {
                            Id = 20,
                            Category = "adult",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6231),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "sex"
                        },
                        new
                        {
                            Id = 21,
                            Category = "adult",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6231),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "phim nguoi lon"
                        },
                        new
                        {
                            Id = 22,
                            Category = "adult",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6232),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "khieu dam"
                        },
                        new
                        {
                            Id = 23,
                            Category = "adult",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6232),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "dam o"
                        },
                        new
                        {
                            Id = 24,
                            Category = "adult",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6233),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "裸"
                        },
                        new
                        {
                            Id = 30,
                            Category = "weapons",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6234),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "vu khi"
                        },
                        new
                        {
                            Id = 31,
                            Category = "weapons",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6234),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "sung luc"
                        },
                        new
                        {
                            Id = 32,
                            Category = "weapons",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6235),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "luu dan"
                        },
                        new
                        {
                            Id = 33,
                            Category = "weapons",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6235),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "bom"
                        },
                        new
                        {
                            Id = 34,
                            Category = "weapons",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6236),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "thuoc no"
                        },
                        new
                        {
                            Id = 35,
                            Category = "weapons",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6236),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "dao gam"
                        },
                        new
                        {
                            Id = 50,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6237),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "suicide"
                        },
                        new
                        {
                            Id = 51,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6237),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "kill someone"
                        },
                        new
                        {
                            Id = 52,
                            Category = "drug",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6238),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "drugs"
                        },
                        new
                        {
                            Id = 53,
                            Category = "adult",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6238),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "porn"
                        },
                        new
                        {
                            Id = 54,
                            Category = "weapons",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6239),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "weapon"
                        },
                        new
                        {
                            Id = 55,
                            Category = "weapons",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6239),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "bomb"
                        },
                        new
                        {
                            Id = 56,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6240),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "terrorist"
                        },
                        new
                        {
                            Id = 57,
                            Category = "violence",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6240),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "murder"
                        },
                        new
                        {
                            Id = 100,
                            Category = "AI_SAFETY",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6240),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "ignore previous instructions"
                        },
                        new
                        {
                            Id = 101,
                            Category = "AI_SAFETY",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6242),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "ignore all instructions"
                        },
                        new
                        {
                            Id = 102,
                            Category = "AI_SAFETY",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6242),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "system prompt"
                        },
                        new
                        {
                            Id = 103,
                            Category = "AI_SAFETY",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6243),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "developer message"
                        },
                        new
                        {
                            Id = 104,
                            Category = "AI_SAFETY",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6243),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "pretend you are"
                        },
                        new
                        {
                            Id = 105,
                            Category = "AI_SAFETY",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6244),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "act as if you are"
                        },
                        new
                        {
                            Id = 106,
                            Category = "AI_SAFETY",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6244),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "jailbreak"
                        },
                        new
                        {
                            Id = 107,
                            Category = "AI_SAFETY",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6245),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "dan mode"
                        },
                        new
                        {
                            Id = 108,
                            Category = "AI_SAFETY",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6245),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "do anything now"
                        },
                        new
                        {
                            Id = 109,
                            Category = "AI_SAFETY",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6246),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "bypass filter"
                        },
                        new
                        {
                            Id = 110,
                            Category = "AI_SAFETY",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6246),
                            CreatedBy = "system",
                            IsActive = true,
                            Word = "you are no longer an ai"
                        });
                });

            modelBuilder.Entity("SmartBearServer.Model.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastInteractionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_interaction_time");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "IsActive");

                    b.ToTable("chat_sessions");
                });

            modelBuilder.Entity("SmartBearServer.Model.ChildProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("BearName")
                        .HasColumnType("text");

                    b.Property<string>("BlockedTopics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ComplexityLevel")
                        .HasColumnType("integer");

                    b.Property<int>("CreativityLevel")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DailyCandyBalance")
                        .HasColumnType("integer")
                        .HasColumnName("daily_candy_balance");

                    b.Property<int>("DailyCandyLimit")
                        .HasColumnType("integer")
                        .HasColumnName("daily_candy_limit");

                    b.Property<int>("EmotionLevel")
                        .HasColumnType("integer");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("Honorific")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastQuotaResetUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_quota_reset_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personality")
                        .HasColumnType("text");

                    b.Property<string>("PersonalityDescription")
                        .HasColumnType("text");

                    b.Property<string>("PreferredTtsProvider")
                        .HasColumnType("text");

                    b.Property<string>("PreferredVoiceId")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("SafetyPretendMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("safety_pretend_message");

                    b.Property<int>("SafetyResponseMode")
                        .HasColumnType("integer")
                        .HasColumnName("safety_response_mode");

                    b.Property<string>("SafetyWarningMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("safety_warning_message");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChildProfiles");
                });

            modelBuilder.Entity("SmartBearServer.Model.DailyUsage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AiRequestCount")
                        .HasColumnType("integer");

                    b.Property<int>("AudioSecondsUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "DateUtc")
                        .IsUnique();

                    b.ToTable("DailyUsages");
                });

            modelBuilder.Entity("SmartBearServer.Model.DemoVoice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GcsPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DemoVoices");
                });

            modelBuilder.Entity("SmartBearServer.Model.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHardwareProtectionEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_protected");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.Property<string>("PairingCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("pairing_code");

                    b.Property<DateTime?>("PairingCodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pairing_code_expires_at");

                    b.Property<float>("PreferredSpeed")
                        .HasColumnType("real")
                        .HasColumnName("preferred_speed");

                    b.Property<float>("PreferredVolume")
                        .HasColumnType("real")
                        .HasColumnName("preferred_volume");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DeviceId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("bear_devices");
                });

            modelBuilder.Entity("SmartBearServer.Model.DeviceCredential", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "TokenHash")
                        .IsUnique();

                    b.ToTable("DeviceCredentials");
                });

            modelBuilder.Entity("SmartBearServer.Model.InteractionHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("history_id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsSafe")
                        .HasColumnType("boolean")
                        .HasColumnName("is_safe");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.Property<string>("SafetyViolationCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("safety_violation_category");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SessionId");

                    b.ToTable("interaction_histories");
                });

            modelBuilder.Entity("SmartBearServer.Model.PendingOrder", b =>
                {
                    b.Property<long>("OrderCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderCode"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<int>("CandyQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("candy_quantity");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fulfilled");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_type");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VoucherCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("voucher_code");

                    b.HasKey("OrderCode");

                    b.ToTable("pending_orders");
                });

            modelBuilder.Entity("SmartBearServer.Model.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("RoleId");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            ColorHex = "#FF0000",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6316),
                            Description = "System Master Administrator with full access.",
                            Icon = "admin_panel_settings",
                            IsActive = true,
                            IsSystem = true,
                            Priority = 0,
                            RoleName = "Master",
                            UpdatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6317)
                        },
                        new
                        {
                            RoleId = 2,
                            ColorHex = "#00FF00",
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6320),
                            Description = "Standard regular user.",
                            Icon = "person",
                            IsActive = true,
                            IsSystem = true,
                            Priority = 10,
                            RoleName = "User",
                            UpdatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6321)
                        });
                });

            modelBuilder.Entity("SmartBearServer.Model.SmartAlarm", b =>
                {
                    b.Property<string>("AlarmId")
                        .HasColumnType("text")
                        .HasColumnName("alarm_id");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("audio_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<int>("Hour")
                        .HasColumnType("integer")
                        .HasColumnName("hour");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<int>("RepeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_count");

                    b.Property<string>("RepeatMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repeat_mode");

                    b.Property<bool>("UseVoice")
                        .HasColumnType("boolean")
                        .HasColumnName("use_voice");

                    b.Property<string>("WakeUpMessage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("wake_up_message");

                    b.HasKey("AlarmId");

                    b.HasIndex("DeviceId");

                    b.ToTable("smart_alarms");
                });

            modelBuilder.Entity("SmartBearServer.Model.Song", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GcsPath")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("SmartBearServer.Model.Story", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GcsPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("SmartBearServer.Model.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanPlayMusic")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanTellStoriesOnUserSpeech")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUseLearningAI")
                        .HasColumnType("boolean");

                    b.Property<int>("DailyCandyLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanType")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceMonthly")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanPlayMusic = true,
                            CanTellStoriesOnUserSpeech = true,
                            CanUseLearningAI = false,
                            DailyCandyLimit = 10,
                            Description = "Trải nghiệm cơ bản: 10 viên kẹo mỗi ngày, nhạc miễn phí.",
                            IsActive = true,
                            Name = "Gói Cơ Bản",
                            PlanType = 1,
                            PriceMonthly = 0m
                        },
                        new
                        {
                            Id = 2,
                            CanPlayMusic = true,
                            CanTellStoriesOnUserSpeech = true,
                            CanUseLearningAI = true,
                            DailyCandyLimit = 50,
                            Description = "Không giới hạn kẹo, giọng đọc cao cấp, học Toán & Tiếng Anh.",
                            IsActive = true,
                            Name = "Gói Nâng Cao",
                            PlanType = 2,
                            PriceMonthly = 100000m
                        },
                        new
                        {
                            Id = 3,
                            CanPlayMusic = true,
                            CanTellStoriesOnUserSpeech = true,
                            CanUseLearningAI = true,
                            DailyCandyLimit = 300,
                            Description = "Siêu cấp: 300 viên kẹo mỗi ngày, không giới hạn tính năng.",
                            IsActive = true,
                            Name = "Gói Ultra",
                            PlanType = 3,
                            PriceMonthly = 350000m
                        });
                });

            modelBuilder.Entity("SmartBearServer.Model.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FreeDailyCreditsLastReset")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("free_daily_credits_last_reset");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsPro")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pro");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredTtsProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preferred_tts_provider");

                    b.Property<string>("PreferredVoiceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("preferred_voice_id");

                    b.Property<DateTime?>("ProExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pro_expires_at");

                    b.Property<string>("Provider")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_id");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("SmartCandies")
                        .HasColumnType("integer")
                        .HasColumnName("smart_candies");

                    b.Property<int?>("SubscriptionPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_plan_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6365),
                            Email = "admin@admin.com",
                            FreeDailyCreditsLastReset = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6338),
                            FullName = "Master Administrator",
                            IsPro = false,
                            PasswordHash = "$2a$11$wqjr5Joq.8ZCu0WFzKTWS..sobu6cqhPGXPNx4hdHUrkbfFxuuM9K",
                            PreferredTtsProvider = "GCP",
                            PreferredVoiceId = "vi-VN-Neural2-A",
                            Provider = "Local",
                            RefreshToken = "",
                            RoleId = 1,
                            SmartCandies = 10,
                            UpdatedAt = new DateTime(2026, 5, 4, 2, 39, 54, 838, DateTimeKind.Utc).AddTicks(6365)
                        });
                });

            modelBuilder.Entity("SmartBearServer.Model.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("CurrentUsage")
                        .HasColumnType("integer")
                        .HasColumnName("current_usage");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DiscountPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percentage");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<int?>("FixedDiscountValue")
                        .HasColumnType("integer")
                        .HasColumnName("fixed_discount_value");

                    b.Property<int?>("FlatPriceValue")
                        .HasColumnType("integer")
                        .HasColumnName("flat_price_value");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxUsage")
                        .HasColumnType("integer")
                        .HasColumnName("max_usage");

                    b.HasKey("Id");

                    b.ToTable("vouchers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DEMO67",
                            CurrentUsage = 0,
                            ExpiryDate = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FixedDiscountValue = 98000,
                            IsActive = true,
                            MaxUsage = 1000
                        },
                        new
                        {
                            Id = 2,
                            Code = "DEMODONGGIA2K",
                            CurrentUsage = 0,
                            Description = "Mã kiểm thử: Đồng giá tất cả dịch vụ 2,000đ",
                            ExpiryDate = new DateTime(2035, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlatPriceValue = 2000,
                            IsActive = true,
                            MaxUsage = 9999
                        });
                });

            modelBuilder.Entity("SmartBearServer.Model.ChildProfile", b =>
                {
                    b.HasOne("SmartBearServer.Model.User", "ParentUser")
                        .WithMany("ChildProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("SmartBearServer.Model.Device", b =>
                {
                    b.HasOne("SmartBearServer.Model.ChildProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBearServer.Model.User", "ParentUser")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentUser");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SmartBearServer.Model.InteractionHistory", b =>
                {
                    b.HasOne("SmartBearServer.Model.ChildProfile", null)
                        .WithMany("Interactions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBearServer.Model.ChatSession", "Session")
                        .WithMany("Interactions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SmartBearServer.Model.SmartAlarm", b =>
                {
                    b.HasOne("SmartBearServer.Model.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SmartBearServer.Model.User", b =>
                {
                    b.HasOne("SmartBearServer.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBearServer.Model.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanId");

                    b.Navigation("Role");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("SmartBearServer.Model.ChatSession", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("SmartBearServer.Model.ChildProfile", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("SmartBearServer.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartBearServer.Model.User", b =>
                {
                    b.Navigation("ChildProfiles");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
